version: "3.5"

services:
  dev:
    build: "./"
    working_dir: "/work/"
    command: ["sleep", "infinity"]
    volumes:
      - "./:/work/:delegated"
    #ports:
    #  - "${APP_PORT}:80"

  api:
    image: "ubuntu"

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator

  postgres:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main

  